"use client";

import React, { useEffect } from "react";
import {
  X,
  Printer,
  Copy,
  Download,
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  FileCheck,
  CheckCircle2,
  ExternalLink,
  Layers,
  Lock,
  Calendar,
  Clock,
  Sparkles,
} from "lucide-react";
import { useToast } from "./ToastContext";

export interface SecurityReportData {
  scanId: string;
  timestamp: string;
  sourceType: "Text" | "Email" | "URL" | "Image OCR" | "QR Code" | "File";
  contentPreview: string;
  overallRisk: number;
  threatLevel: "SAFE" | "LOW_RISK" | "SUSPICIOUS" | "HIGH_RISK" | "CRITICAL";
  modelUsed: string;
  confidence: number;
  spamProbability: number;
  riskBreakdown: {
    contentRisk: number;
    urlRisk: number;
    languageRisk: number;
    urgencyRisk: number;
    manipulationRisk: number;
    senderRisk: number;
    attachmentRisk: number;
  };
  detectedSignals: string[];
  keyFeatures: Array<{ term: string; weight: number; direction: string }>;
  recommendations: string[];
  explanation: string;
}

interface SecurityReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: SecurityReportData | null;
}

export default function SecurityReportModal({ isOpen, onClose, report }: SecurityReportModalProps) {
  const { toast } = useToast();

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    if (isOpen) {
      document.body.style.overflow = "hidden";
      window.addEventListener("keydown", handleKeyDown);
    }
    return () => {
      document.body.style.overflow = "unset";
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [isOpen, onClose]);

  if (!isOpen || !report) return null;

  const isThreat = report.overallRisk >= 40;
  const levelBadgeColors = {
    SAFE: "bg-emerald-50 text-emerald-800 border-emerald-200",
    LOW_RISK: "bg-teal-50 text-teal-800 border-teal-200",
    SUSPICIOUS: "bg-amber-50 text-amber-800 border-amber-200",
    HIGH_RISK: "bg-orange-50 text-orange-800 border-orange-200",
    CRITICAL: "bg-rose-50 text-rose-800 border-rose-200",
  }[report.threatLevel] || "bg-slate-50 text-slate-700 border-slate-200";

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = `
# SpamGuard Threat Intelligence Security Report
**Scan ID:** ${report.scanId}
**Date/Time:** ${report.timestamp}
**Target Type:** ${report.sourceType}
**Overall Threat Level:** ${report.threatLevel} (Risk Score: ${report.overallRisk}/100)
**AI Model:** ${report.modelUsed} (${(report.confidence * 100).toFixed(1)}% Confidence)

## Content Summary
> ${report.contentPreview.slice(0, 300)}

## Risk Factor Breakdown
- Content Risk: ${report.riskBreakdown.contentRisk}/100
- URL Threat Risk: ${report.riskBreakdown.urlRisk}/100
- Language & Urgency: ${report.riskBreakdown.urgencyRisk}/100
- Social Engineering / Manipulation: ${report.riskBreakdown.manipulationRisk}/100
- Sender Authenticity: ${report.riskBreakdown.senderRisk}/100

## Detected Threat Markers
${report.detectedSignals.map((s) => `- ${s}`).join("\n")}

## Recommended Security Protocol
${report.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

---
*Generated by SpamGuard AI Security Platform.*
`.trim();

    navigator.clipboard.writeText(md);
    toast("Security report copied to clipboard (Markdown format)", "success");
  };

  const handleDownloadJson = () => {
    const jsonStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", jsonStr);
    downloadAnchor.setAttribute("download", `SpamGuard-Security-Report-${report.scanId}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    toast("Report downloaded as JSON", "success");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-900/40 backdrop-blur-xs">
      <div className="relative w-full max-w-3xl max-h-[90vh] bg-white rounded-2xl border border-slate-200 shadow-2xl flex flex-col overflow-hidden text-slate-800">
        {/* Modal Top Bar */}
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-indigo-50 border border-indigo-200 flex items-center justify-center text-indigo-600">
              <FileCheck className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 tracking-tight">Security Audit Report</h3>
              <p className="text-[11px] font-mono text-slate-400">Dossier ID: {report.scanId}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-2.5 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-600 hover:bg-slate-100 transition-colors inline-flex items-center gap-1.5 cursor-pointer print:hidden"
              title="Print dossier"
            >
              <Printer className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Print</span>
            </button>
            <button
              onClick={handleCopyMarkdown}
              className="px-2.5 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-600 hover:bg-slate-100 transition-colors inline-flex items-center gap-1.5 cursor-pointer"
              title="Copy markdown"
            >
              <Copy className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Copy MD</span>
            </button>
            <button
              onClick={handleDownloadJson}
              className="px-2.5 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-600 hover:bg-slate-100 transition-colors inline-flex items-center gap-1.5 cursor-pointer"
              title="Download JSON"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">JSON</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-xs print:p-0">
          {/* Executive Header Banner */}
          <div className="p-4 rounded-xl border flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-50/80 border-slate-200">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase tracking-wider border ${levelBadgeColors}`}>
                  {report.threatLevel.replace("_", " ")}
                </span>
                <span className="text-slate-400 font-mono">Channel: {report.sourceType}</span>
              </div>
              <p className="text-sm font-bold text-slate-900">
                {isThreat ? "Critical Threat Signals Identified" : "Verified Safe Communication"}
              </p>
              <p className="text-[11px] text-slate-500 font-mono mt-0.5">
                Timestamp: {report.timestamp} &bull; Model: {report.modelUsed}
              </p>
            </div>

            <div className="flex sm:flex-col items-center sm:items-end justify-between border-t sm:border-t-0 pt-2 sm:pt-0 border-slate-200">
              <span className="text-[10px] uppercase font-bold text-slate-400">Composite Risk</span>
              <div className="flex items-baseline gap-1">
                <span className={`text-3xl font-black font-mono tracking-tight ${isThreat ? "text-rose-600" : "text-emerald-600"}`}>
                  {report.overallRisk}
                </span>
                <span className="text-slate-400 text-xs">/100</span>
              </div>
            </div>
          </div>

          {/* Explanation Synopsis */}
          <div>
            <h4 className="text-[11px] font-bold uppercase text-slate-400 tracking-wider mb-2">
              Executive AI Threat Explanation
            </h4>
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 text-slate-700 leading-relaxed font-sans">
              {report.explanation}
            </div>
          </div>

          {/* Multidimensional Threat Vectors */}
          <div>
            <h4 className="text-[11px] font-bold uppercase text-slate-400 tracking-wider mb-2">
              Multi-Vector Risk Matrix
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
              {Object.entries(report.riskBreakdown).map(([factor, score]) => {
                const label = factor.replace("Risk", "").replace(/([A-Z])/g, " $1").trim();
                const isHigh = score >= 50;
                return (
                  <div key={factor} className="p-3 rounded-xl bg-white border border-slate-200 flex flex-col justify-between">
                    <span className="text-[10px] uppercase font-bold text-slate-500 capitalize">{label} Risk</span>
                    <div className="mt-2 flex items-baseline justify-between">
                      <span className={`text-lg font-black font-mono ${isHigh ? "text-rose-600" : "text-slate-700"}`}>
                        {score}
                      </span>
                      <span className="text-[10px] text-slate-400">/100</span>
                    </div>
                    <div className="w-full h-1 bg-slate-100 rounded-full mt-1.5 overflow-hidden">
                      <div
                        className={`h-full rounded-full ${isHigh ? "bg-rose-500" : "bg-emerald-500"}`}
                        style={{ width: `${Math.min(score, 100)}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Detected Threat Flags */}
          {report.detectedSignals.length > 0 && (
            <div>
              <h4 className="text-[11px] font-bold uppercase text-slate-400 tracking-wider mb-2">
                Identified Threat Signals &amp; Risk Triggers ({report.detectedSignals.length})
              </h4>
              <div className="flex flex-wrap gap-2">
                {report.detectedSignals.map((signal, idx) => (
                  <span
                    key={idx}
                    className="px-2.5 py-1 rounded-lg bg-rose-50 border border-rose-200 text-rose-700 font-mono text-[11px] flex items-center gap-1.5"
                  >
                    <AlertTriangle className="w-3 h-3 shrink-0" />
                    <span>{signal}</span>
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Statistical Features */}
          {report.keyFeatures.length > 0 && (
            <div>
              <h4 className="text-[11px] font-bold uppercase text-slate-400 tracking-wider mb-2">
                Top Empirical TF-IDF Feature Contributions
              </h4>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                {report.keyFeatures.slice(0, 8).map((f, i) => (
                  <div
                    key={i}
                    className={`p-2.5 rounded-lg border text-xs flex items-center justify-between font-mono ${
                      f.direction === "spam" ? "bg-rose-50/50 border-rose-200 text-rose-800" : "bg-emerald-50/50 border-emerald-200 text-emerald-800"
                    }`}
                  >
                    <span className="font-bold truncate">{f.term}</span>
                    <span className="text-[10px] font-semibold">{f.weight > 0 ? `+${f.weight.toFixed(2)}` : f.weight.toFixed(2)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Contextual Recommendations */}
          <div>
            <h4 className="text-[11px] font-bold uppercase text-slate-400 tracking-wider mb-2">
              Recommended Security Protocol &bull; Action Items
            </h4>
            <div className="space-y-2">
              {report.recommendations.map((rec, i) => (
                <div
                  key={i}
                  className="p-2.5 rounded-xl bg-white border border-slate-200 flex items-start gap-2.5 text-xs text-slate-700"
                >
                  <div className="w-5 h-5 rounded-full bg-slate-100 flex items-center justify-center text-[10px] font-bold text-slate-600 shrink-0 mt-0.5">
                    {i + 1}
                  </div>
                  <span className="leading-snug">{rec}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3 border-t border-slate-100 bg-slate-50 flex items-center justify-between text-[11px] text-slate-400 font-mono">
          <span>SpamGuard Cyber Intelligence Platform</span>
          <button onClick={onClose} className="px-3 py-1 bg-white border border-slate-200 rounded-lg text-slate-600 hover:bg-slate-100 transition-colors font-sans font-semibold">
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
}
